# Generated by Django 4.2.7 on 2023-11-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_movie_description_alter_movie_title_cz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
