# Generated by Django 4.2.7 on 2023-12-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_comment_created_comment_updated_movie_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title_orig']},
        ),
    ]
