# Generated by Django 4.2.7 on 2023-12-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_remove_image_url_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
